name: biophys
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - astropy=7.1.0
  - astropy-iers-data=0.2025.6.23.0.39.50
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jpeg=9e
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libkrb5=1.21.3
  - libmpdec=4.0.0
  - libpng=1.6.39
  - libpq=17.4
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pyerfa=2.0.1.5
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - scipy=1.16.0
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
